backend: pytorch
env:
  clevr:
    variables:
      dataset: src.clevr.CLEVR
  gqa:
    variables:
      dataset: src.gqa.GQA
model:
  name: src.mac.MAC
  dim: 512
  embed_dim: 300
  max_step: 12
  self_attention: true
  memory_gate: true
  dropout: 0.15
dataset:
  name: ~dataset
train:
  eval: [valid]
  num_epochs: 25
  batch_size: 32
  optimizer:
    name: adam
    lr: 0.0001
  log_every: 0.1e
test:
  log_every: 5s