backend: pytorch
model:
  name: src.torch.models.nsm.NSM
  embed_dim: 300
  encoder:
    type: lstm
  decoder:
    type: lstm
  num_steps: 8
  dropout: 0.15
dataset:
  name: src.datasets.gqa.GQA
  balanced: true
  object_features: true
  embeddings:
    pretrained: glove
train:
  num_epochs: 15
  batch_size: 32
  optimizer:
    name: adam
    gamma: 1e-4
test:
  test_sets: [valid]